// 构建元数据：VERGEN_BUILD_* / VERGEN_GIT_*（调 git CLI，§2 禁 git2）。
// git 不可用时 vergen 默认 fail_on_error=false，降级为 "unknown" 并出 cargo:warning。
// 另：FFI 调用 shim 代码生成（bun:ffi，§13 手写件）——见本目录 emit_ffi_shims。
use vergen_gitcl::{Build, Emitter, Gitcl};

fn main() {
    let result = (|| -> Result<(), Box<dyn std::error::Error>> {
        let build = Build::all_build();
        let gitcl = Gitcl::all_git();
        Emitter::default()
            .add_instructions(&build)?
            .add_instructions(&gitcl)?
            .emit()?;
        emit_ffi_shims()?;
        Ok(())
    })();
    if let Err(e) = result {
        println!("cargo:warning=winterjs: build metadata unavailable: {e}");
    }
}

// ── bun:ffi 调用 shim 生成 ────────────────────────────────────────────────
// 原理：C ABI（SysV x86_64/arm64、Win64）按参数独立分类——整数/指针走 INTEGER
// 寄存器，float/double 走 SSE 寄存器。`extern "C" fn(target, a0..an) -> R` 形状的
// 中转函数对目标函数完全 ABI 透明（编译器自己完成收/发两侧的寄存器搬移，含栈参）。
// 为每个 (元数, 双精度参数位置掩码, 返回类别) 生成一个 shim，运行时按签名查表调用
// —— 这就是无 libffi 的动态调用引擎（纯 Rust，零新依赖；limitations 见 ffi.rs 头注）。
//
// 类别：arg = I(usize，整数/指针/布尔) | D(f64)；ret = 0:I(usize) | 1:D(f64) | 2:F(f32)。
// f32 参数不支持（SSE 单精度编码与 f64 不同，展开成 3^n 个 shim 不划算），
// 返回 f32 单独一类。结构体按值传参/返回不支持。
fn emit_ffi_shims() -> Result<(), Box<dyn std::error::Error>> {
    const MAX_ARITY: usize = 6;
    let mut out = String::from(
        "// @generated by build.rs（bun:ffi 调用 shim）——勿手改，改生成器。\n\n\
         /// FFI 调用结果（按返回类别）。\n\
         #[derive(Debug, Clone, PartialEq)]\n\
         pub enum FfiRet { I(u64), D(f64), F(f32) }\n\n",
    );
    for arity in 0..=MAX_ARITY {
        for mask in 0..(1u64 << arity) {
            for ret in 0..3u8 {
                let mut params = Vec::with_capacity(arity);
                let mut types = Vec::with_capacity(arity);
                for i in 0..arity {
                    let ty = if mask & (1 << i) != 0 { "f64" } else { "usize" };
                    params.push(format!("a{i}: {ty}"));
                    types.push(ty.to_string());
                }
                let ret_ty = match ret { 0 => "usize", 1 => "f64", _ => "f32" };
                out.push_str(&format!(
                    "#[allow(unused_variables)]\n\
                     extern \"C\" fn shim_{arity}_{mask}_{ret}(target: usize, {params}) -> {ret_ty} {{\n\
                     unsafe {{\n\
                     let f: extern \"C\" fn({types}) -> {ret_ty} = std::mem::transmute(target);\n\
                     f({call})\n\
                     }}\n\
                     }}\n\n",
                    params = params.join(", "),
                    types = types.join(", "),
                    call = (0..arity).map(|i| format!("a{i}")).collect::<Vec<_>>().join(", "),
                ));
            }
        }
    }
    out.push_str(
        "/// 按 (元数, 双精度位置掩码, 返回类别) 查 shim 并调用。\n\
         /// # Safety\n\
         /// `target` 须为真实可调用的 C 函数地址，签名与 (arity, mask, ret) 一致；\n\
         /// `iargs`/`dargs` 长度须与掩码展开后的实参数一致。\n\
         pub unsafe fn invoke(arity: usize, mask: u64, ret: u8, target: usize, iargs: &[u64], dargs: &[f64]) -> Result<FfiRet, ()> {\n\
         let r = match (arity, mask, ret) {\n",
    );
    for arity in 0..=MAX_ARITY {
        for mask in 0..(1u64 << arity) {
            for ret in 0..3u8 {
                let (mut ii, mut di) = (0usize, 0usize);
                let mut call = Vec::with_capacity(arity);
                for i in 0..arity {
                    if mask & (1 << i) != 0 {
                        call.push(format!("dargs[{di}]"));
                        di += 1;
                    } else {
                        call.push(format!("iargs[{ii}] as usize"));
                        ii += 1;
                    }
                }
                let tag = match ret { 0 => "I", 1 => "D", _ => "F" };
                out.push_str(&format!(
                    "        ({arity}, {mask}, {ret}) => FfiRet::{tag}(shim_{arity}_{mask}_{ret}(target, {call}) as _),\n",
                    call = call.join(", "),
                ));
            }
        }
    }
    out.push_str(
        "        _ => return Err(()),\n\
         };\n\
         Ok(r)\n\
         }\n",
    );
    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(format!("{out_dir}/ffi_shims.rs"), out)?;
    println!("cargo:rerun-if-changed=build.rs");
    Ok(())
}
